### ISSUE TITLE
Disconnecting USB Port does not stop main loop

### ISSUE THREAD

**Issue by corytodd** [PyramidTechnologies/PTI.Rs232Validator#3]
There are checks in place for losing connecting to the device but if you unplug the serial harness, the check does not appear to work as expected. ApexValidator Serial provider is not open will be reported at ERROR level forever.

We should make this part of the connection lost event and break the processing loop.

**Comment by codygillespie** [comment]
I believe this was all that was missing: https://github.com/PyramidTechnologies/PTI.Rs232Validator/compare/feature/issue-3-disconnecting-usb-port-does-not-stop-main-loop?expand=1

**Comment by corytodd** [comment]
Resolved by #4 , thank you

Let's get this pushed to nuget before end of week

**Comment by codygillespie** [comment]
This is now available on Nuget:

https://www.nuget.org/packages/PTI.Rs232Validator/1.1.1
